### PR TITLE
Added port of polymer-ui-clock.

### PR DESCRIPTION
**Pull request by chankh**

### CODE REVIEW

**Comment by zoechi** [comment]
Hi chankh,
that's great!
I'll check it tomorrow. I'm currently on a problem that needs my full attention...
Can't wait to see it though.
Cheers
Günter

**Comment by zoechi** [comment]
Love it!
The [JavaScript polymer-ui-clock demo page](http://www.polymer-project.org/components/polymer-ui-clock/smoke.html) doesn't show the date/time at the bottom of the clock. Is their demo page outdated or did you invent that feature?
It's fine, but I would remove the milliseconds because it looks weird that they get updated only once a second.
Thanks for contributing!

**Comment by chankh** [comment]
I found that the date/time was just hidden in the JavaScript demo page, so I decided to extend the height of the element to include that.

I had the thoughts of porting polymer-ui-elements to Dart and realized that you had already did most of it. I will be free for some time, so would just like to contribute. Cheers!

**Comment by zoechi** [comment]
It would be great!
The repo got a bit stale because we run into so many bugs and work got really hard. But Polymer made a lot of progress lately.
If you have any questions don't hesitate to create an issue.

I saw that the [background of the clock is not shown when built to JavaScript](http://erikgrimes.github.io/polymer_elements/build_ui/polymer_ui_clock.html) but that's the same with the original JS demo page. But it's shown here http://kylescholz.com/projects/Polymer/polymer-ui-elements/polymer-ui-clock/ (no idea what project that is)

**Comment by chankh** [comment]
The background image is missing in the link below.

http://erikgrimes.github.io/polymer_elements/lib/asset/glass.png

**Pull request merged**
